# Generated by Django 5.1.1 on 2025-08-19 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_game_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='player_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
