# Generated by Django 5.1.1 on 2025-08-19 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_score_player_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='player',
            field=models.ForeignKey(blank=True, db_column='player_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
